In [35]:
# library for working with dataframes (matrics)
import pandas as pd

In [36]:
ls datasets/kaggle/stage_2

Cities.csv*                         RegularSeasonCompactResults.csv*
ConferenceTourneyGames.csv*         RegularSeasonDetailedResults.csv*
Conferences.csv*                    Seasons.csv*
GameCities.csv*                     SecondaryTourneyCompactResults.csv*
NCAATourneyCompactResults.csv*      SecondaryTourneyTeams.csv*
NCAATourneyDetailedResults.csv*     TeamCoaches.csv*
NCAATourneySeedRoundSlots.csv*      TeamConferences.csv*
NCAATourneySeeds.csv*               TeamSpellings.csv*
NCAATourneySlots.csv*               Teams.csv*


In [37]:
# Define file paths
FILE_PATH = 'datasets/kaggle/stage_2/'
NCAATourneyCompactResults_path = FILE_PATH + 'NCAATourneyCompactResults.csv'
NCAATourneySeeds_path = FILE_PATH + 'NCAATourneySeeds.csv'
RegularSeasonCompactResults_path = FILE_PATH + 'RegularSeasonCompactResults.csv'

In [38]:
# Create dataframes from files
NCAATourneyCompactResults = pd.read_csv(NCAATourneyCompactResults_path)
NCAATourneySeeds = pd.read_csv(NCAATourneySeeds_path)
RegularSeasonCompactResults = pd.read_csv(RegularSeasonCompactResults_path)

In [39]:
# Look at dataframes
NCAATourneyCompactResults.head()

Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985     136     1116      63     1234      54    N      0
1    1985     136     1120      59     1345      58    N      0
2    1985     136     1207      68     1250      43    N      0
3    1985     136     1229      58     1425      55    N      0
4    1985     136     1242      49     1325      38    N      0

In [40]:
NCAATourneySeeds.head()

Season Seed  TeamID
0    1985  W01    1207
1    1985  W02    1210
2    1985  W03    1228
3    1985  W04    1260
4    1985  W05    1374

In [41]:
RegularSeasonCompactResults.head()

Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985      20     1228      81     1328      64    N      0
1    1985      25     1106      77     1354      70    H      0
2    1985      25     1112      63     1223      56    H      0
3    1985      25     1165      70     1432      54    H      0
4    1985      25     1192      86     1447      74    H      0

## Create a 'seed' DataFrame

In [42]:
# Define a function that combines the values of two DataFrame columns,
# combining them into a single column with the values separated by an underscore
def get_id(p_row, p_column_names):
    column_values = [p_row[col] for col in p_column_names]
    return '_'.join(map(str, column_values))


# Make a copy of the NCAATourneySeeds DataFrame
seed = NCAATourneySeeds.copy()
# Add an 'id' column to the 'seed' DataFrame,
# using the get_id function to combine 'Season' and 'TeamID'
seed['id'] = seed.apply(lambda row: get_id(row, ['Season', 'TeamID']), axis=1)
# Extract the seed number from the 'Seed' value
seed['seed'] = seed['Seed'].apply(lambda x: int(x[1:3]))
# Extract the region from the 'Seed' value
seed['region'] = seed['Seed'].apply(lambda x: x[0])
# Rename the 'Season' column to 'season' and 'TeamID' to 'team'
seed = seed.rename(columns={'Season': 'season', 'TeamID': 'team'})
# Redefine the 'seed' DataFrame with the columns in this order
seed = seed[['id', 'season', 'team', 'region', 'seed']]
# Sort the 'seed' DataFrame by the 'id' column we created
seed = seed.sort_values(by=['id'])
seed.head()

id  season  team region  seed
22  1985_1104    1985  1104      X     7
25  1985_1112    1985  1112      X    10
24  1985_1116    1985  1116      X     9
58  1985_1120    1985  1120      Z    11
42  1985_1130    1985  1130      Y    11

In [43]:
# Look at NCAATourneyCompactResults
NCAATourneyCompactResults.head()
# Note 

Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985     136     1116      63     1234      54    N      0
1    1985     136     1120      59     1345      58    N      0
2    1985     136     1207      68     1250      43    N      0
3    1985     136     1229      58     1425      55    N      0
4    1985     136     1242      49     1325      38    N      0

## Create a 'final_four' DataFrame

In [44]:
# Create a 'tourney' DataFrame based on NCAATourneyCompactResults
tourney = NCAATourneyCompactResults.copy()
# Create a 'winners' DataFrame
winners = tourney[['Season', 'DayNum', 'WTeamID', 'WScore', 'NumOT']].copy()
# Rename the columns
winners = winners.rename(columns={'WTeamID': 'TeamID', \
                                  'WScore': 'Score'
                                 })
# Create a 'losers' DataFrame
losers = tourney[['Season', 'DayNum', 'LTeamID', 'LScore', 'NumOT']].copy()
# Rename the columns
losers = losers.rename(columns={'LTeamID': 'TeamID', \
                                'LScore': 'Score'
                               })
# Combine the 'winners' and 'losers' DataFrames
results = pd.concat([winners, losers])
# Create a 'final_four' DataFrame for only the teams that played on day 152
final_four = results.loc[results['DayNum'] == 152].copy()
# Create an 'id' column
final_four['id'] = final_four.apply(lambda row: get_id(row, ['Season', 'TeamID']), axis=1)
# Sort the DataFrame by the 'id' column
final_four = final_four[['id']].sort_values(by=['id'])
# Create a 'final_four' column, set it to 1
final_four['final_four'] = str(1) # string
# final_four['final_four'] = 1 # numeric
# Show the first 5 rows
final_four.head()

id final_four
60   1985_1207          1
61   1985_1272          1
60   1985_1385          1
61   1985_1437          1
123  1986_1181          1

## Combine 'seed' and 'final_four' DataFrames

In [45]:
# Merge the 'seed' and 'final_four' DataFrames.
# Left: Keep all the rows from the 'seed' DataFrame,
# even when there's no match in 'final_four'
dataset = pd.merge(seed, final_four, how='left', on='id')
dataset.head()

id  season  team region  seed final_four
0  1985_1104    1985  1104      X     7        NaN
1  1985_1112    1985  1112      X    10        NaN
2  1985_1116    1985  1116      X     9        NaN
3  1985_1120    1985  1120      Z    11        NaN
4  1985_1130    1985  1130      Y    11        NaN

In [46]:
# Set all the 'final_four' column values that aren't 1, to 0
dataset['final_four'] = dataset['final_four'].fillna(value=str(0)) # string
# dataset['final_four'] = dataset['final_four'].fillna(value=0) # numeric
# Show the dataset the way we want it
dataset

id  season  team region  seed final_four
0     1985_1104    1985  1104      X     7          0
1     1985_1112    1985  1112      X    10          0
2     1985_1116    1985  1116      X     9          0
3     1985_1120    1985  1120      Z    11          0
4     1985_1130    1985  1130      Y    11          0
5     1985_1173    1985  1173      Z     9          0
6     1985_1177    1985  1177      W    10          0
7     1985_1181    1985  1181      Y     3          0
8     1985_1192    1985  1192      Z    16          0
9     1985_1207    1985  1207      W     1          1
10    1985_1208    1985  1208      W     6          0
11    1985_1210    1985  1210      W     2          0
12    1985_1228    1985  1228      W     3          0
13    1985_1229    1985  1229      Y     9          0
14    1985_1233    1985  1233      W    13          0
15    1985_1234    1985  1234      X     8          0
16    1985_1235    1985  1235      Y    13          0
17    1985_1242    1985  1242      Z     3          0
18    1985_1246    1985  1246      X    12          0
19    1985_1250    1985  1250      W    16          0
20    1985_1256    1985  1256      Y     5          0
21    1985_1260    1985  1260      W     4          0
22    1985_1261    1985  1261      Z     4          0
23    1985_1267    1985  1267      X    15          0
24    1985_1268    1985  1268      Z     5          0
25    1985_1272    1985  1272      Y     2          1
26    1985_1273    1985  1273      W    15          0
27    1985_1275    1985  1275      Z    12          0
28    1985_1276    1985  1276      Z     1          0
29    1985_1277    1985  1277      Y    10          0
...         ...     ...   ...    ...   ...        ...
2256  2019_1305    2019  1305      X     7          0
2257  2019_1308    2019  1308      Y    12          0
2258  2019_1314    2019  1314      Y     1          0
2259  2019_1318    2019  1318      Y    13          0
2260  2019_1326    2019  1326      Y    11          0
2261  2019_1328    2019  1328      Z     9          0
2262  2019_1330    2019  1330      Z    14          0
2263  2019_1332    2019  1332      Z    12          0
2264  2019_1341    2019  1341      X    16          0
2265  2019_1345    2019  1345      Z     3          0
2266  2019_1371    2019  1371      Y    10          0
2267  2019_1385    2019  1385      X    11          0
2268  2019_1387    2019  1387      W    13          0
2269  2019_1388    2019  1388      Z    11          0
2270  2019_1393    2019  1393      X     8          0
2271  2019_1396    2019  1396      W    11          0
2272  2019_1397    2019  1397      Z     2          0
2273  2019_1403    2019  1403      X     3          0
2274  2019_1414    2019  1414      Z    13          0
2275  2019_1416    2019  1416      W     9          0
2276  2019_1429    2019  1429      Y     8          0
2277  2019_1433    2019  1433      W     8          0
2278  2019_1436    2019  1436      X    13          0
2279  2019_1437    2019  1437      Z     6          0
2280  2019_1438    2019  1438      Z     1          0
2281  2019_1439    2019  1439      W     4          0
2282  2019_1449    2019  1449      Y     9          0
2283  2019_1458    2019  1458      Z     5          0
2284  2019_1459    2019  1459      Y     7          0
2285  2019_1463    2019  1463      W    14          0

[2286 rows x 6 columns]

## Logistic regression

In [47]:
# Create a historical DataFrame (exclude 2019)
dataset_historical = dataset.loc[dataset['season'] != 2019]
dataset_historical.head()

id  season  team region  seed final_four
0  1985_1104    1985  1104      X     7          0
1  1985_1112    1985  1112      X    10          0
2  1985_1116    1985  1116      X     9          0
3  1985_1120    1985  1120      Z    11          0
4  1985_1130    1985  1130      Y    11          0

In [48]:
# Createa 2019 DataFrame
dataset_2019 = dataset.loc[dataset['season'] == 2019]
dataset_2019.head()

id  season  team region  seed final_four
2218  2019_1101    2019  1101      Y    15          0
2219  2019_1113    2019  1113      X    11          0
2220  2019_1120    2019  1120      Y     5          0
2221  2019_1124    2019  1124      X     9          0
2222  2019_1125    2019  1125      W    11          0

In [49]:
# We'll use 'X' for our predictors and 'y' for our target
# We just want the values, and we want it as an array instead of a DataFrame
X = dataset_historical.iloc[:, 4:5].values
X

array([[ 7],
       [10],
       [ 9],
       ...,
       [ 4],
       [14],
       [ 1]])

In [50]:
y = dataset_historical.iloc[:, 5].values
y

array(['0', '0', '0', ..., '0', '0', '0'], dtype=object)

In [51]:
# Split X and y into training and testing datasets
from sklearn.model_selection import train_test_split
X_train, X_test, \
y_train, y_test = \
train_test_split(X, \
                 y, \
                 test_size=0.3, \
                 random_state=0 \
                )

In [52]:
X_train

array([[ 5],
       [ 2],
       [12],
       ...,
       [ 3],
       [ 8],
       [15]])

In [53]:
y_train

array(['0', '0', '0', ..., '0', '0', '0'], dtype=object)

In [54]:
# We want the predictors to be on the same scale
# (mean of 0, standard deviation of 1)
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
# Don't worry about the warning
X_train

/Users/ehelander/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


array([[-0.76140158],
       [-1.40444271],
       [ 0.73902773],
       ...,
       [-1.19009567],
       [-0.11836045],
       [ 1.38206886]])

In [55]:
# Fit a LogisticRegression object to training set
from sklearn.linear_model import LogisticRegression
classifierObj = LogisticRegression(random_state=0)
classifierObj.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [56]:
y_train

array(['0', '0', '0', ..., '0', '0', '0'], dtype=object)

In [57]:
# Making predictions on the test set
y_pred = classifierObj.predict(X_test)

In [58]:
# Evaluating the predictions using a confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[626   0]
 [ 40   0]]


In [59]:
# So, we predicted 0 out of 43 correctly.
# This is to be expected, because the model, by default,
# will only predict a class if it has a greater than
# 50% probability. None of these teams do.

In [60]:
# Predict the probability of [0, 1]
prob = classifierObj.predict_proba(X_test)
prob

array([[0.98396647, 0.01603353],
       [0.9644351 , 0.0355649 ],
       [0.98928431, 0.01071569],
       ...,
       [0.99859609, 0.00140391],
       [0.88845877, 0.11154123],
       [0.9928512 , 0.0071488 ]])

In [63]:
length = dataset_historical.shape[0]
length

2218

In [71]:
train_index_stop = int(length * 0.7)
train_index_stop

1552

In [64]:
import numpy as np

In [72]:
permutation = np.random.RandomState(0).permutation(length)
permutation

array([1444,   98, 1598, ...,  763,  835, 1653])

In [75]:
train_permutation = permutation[:train_index_stop]
train_permutation

array([1444,   98, 1598, ..., 1520,   46,  747])

In [76]:
test_permutation = permutation[train_index_stop:]
test_permutation

array([1746,  753,  462,  673, 1682, 1463, 1201, 2203,  424,  325,  664,
        350,  447, 1625, 1041, 1221, 1712, 1149,  387, 1369, 1743, 1337,
        754,  138,  451, 1194,  699, 1157, 2043,  830, 1102,  950, 1019,
       2110, 1370,  396, 1413, 1409, 1143, 1897, 1177, 1843, 1253, 2044,
         21, 1305,  766,  392,  250, 1267, 1796, 1059,  671, 2087,  845,
       1829, 1646, 1353, 1133, 1403,  869,  604, 2217, 1933,  627,  902,
       1606,  856, 1195, 1262,  700, 1768, 1889,  709,  448,  321, 1932,
        696, 1179, 2051,  624, 2065,  125, 1011, 1480, 1090,  848,  780,
        605,  174, 1883, 1202, 1996,  415,  100, 1270, 2006,  741,  334,
       1974, 2003,  834,  833, 1244, 1415,  594,  939, 1333, 2078,  169,
       1551, 1688, 1269, 1542, 2068, 1739, 2200,  640,  104,  815, 1789,
       1597,  998, 1075, 1626, 1378,  719,  460, 1046, 1398, 1562, 1242,
        585, 2151, 2064, 1389, 1979, 1229, 1522,  497, 1540,  702,  375,
        975, 1209, 1880,  404,  419, 1425, 1734, 19

In [77]:
import numpy as np
length = dataset_historical.shape[0]
permutation = np.random.RandomState(0).permutation(length)
train_permutation = permutation[:train_index_stop]
test_permutation = permutation[train_index_stop:]


In [79]:
dataset_historical.loc[train_permutation]

id  season  team region  seed final_four
1444  2007_1277    2007  1277      W     9          0
98    1986_1298    1986  1298      W     7          0
1598  2009_1425    2009  1425      Y    10          0
768   1997_1112    1997  1112      X     4          1
39    1985_1326    1985  1326      Y     4          0
570   1993_1435    1993  1435      Z     3          0
2215  2018_1455    2018  1455      W     4          0
1287  2005_1130    2005  1130      X     4          0
1051  2001_1232    2001  1232      Z    13          0
942   1999_1373    1999  1373      Z    13          0
587   1994_1181    1994  1181      X     2          1
758   1996_1419    1996  1419      X    15          0
1977  2015_1277    2015  1277      W     7          1
342   1990_1231    1990  1231      W     8          0
721   1996_1210    1996  1210      Y     3          0
1752  2012_1172    2012  1172      Z    13          0
831   1997_1462    1997  1462      Y     7          0
638   1994_1453    1994  1453      Z    12          0
459   1992_1183    1992  1183      X    15          0
512   1993_1112    1993  1112      Z     2          0
264   1989_1166    1989  1166      Y    14          0
1264  2004_1386    2004  1386      Y     1          0
446   1991_1453    1991  1453      Z    12          0
708   1996_1133    1996  1133      W     8          0
1154  2003_1104    2003  1104      Y    10          0
107   1986_1337    1986  1337      Z    12          0
1989  2015_1329    2015  1329      Z     9          0
245   1988_1393    1988  1393      W     3          0
1408  2006_1452    2006  1452      W     6          0
53    1985_1403    1985  1403      Y     6          0
...         ...     ...   ...    ...   ...        ...
1095  2002_1148    2002  1148      Y    14          0
561   1993_1380    1993  1380      Z    13          0
179   1987_1396    1987  1396      Y     2          0
109   1986_1350    1986  1350      W    11          0
1517  2008_1332    2008  1332      Y     9          0
116   1986_1412    1986  1412      Z     6          0
293   1989_1314    1989  1314      Z     2          0
1100  2002_1172    2002  1172      Z    13          0
1072  2001_1381    2001  1381      W    14          0
643   1995_1116    1995  1116      Y     2          1
772   1997_1143    1997  1143      W     5          0
1998  2015_1400    2015  1400      Y    11          0
2157  2018_1139    2018  1139      W    10          0
1356  2006_1133    2006  1133      X    13          0
622   1994_1387    1994  1387      Y     7          0
1964  2015_1211    2015  1211      X     2          0
1968  2015_1234    2015  1234      X     7          0
409   1991_1293    1991  1293      X    13          0
636   1994_1448    1994  1448      X     5          0
115   1986_1409    1986  1409      W    10          0
288   1989_1278    1989  1278      W    11          0
886   1998_1397    1998  1397      X     8          0
1181  2003_1264    2003  1264      W    14          0
337   1990_1210    1990  1210      Y     4          1
1753  2012_1178    2012  1178      X    15          0
2164  2018_1181    2018  1181      X     2          0
1012  2000_1397    2000  1397      X     4          0
1520  2008_1345    2008  1345      Z     6          0
46    1985_1345    1985  1345      Z     6          0
747   1996_1354    1996  1354      Z    15          0

[1552 rows x 6 columns]