In [117]:
# library for working with dataframes (matrics)
import pandas as pd

In [118]:
ls datasets/kaggle/stage_2

Cities.csv*                         RegularSeasonCompactResults.csv*
ConferenceTourneyGames.csv*         RegularSeasonDetailedResults.csv*
Conferences.csv*                    Seasons.csv*
GameCities.csv*                     SecondaryTourneyCompactResults.csv*
NCAATourneyCompactResults.csv*      SecondaryTourneyTeams.csv*
NCAATourneyDetailedResults.csv*     TeamCoaches.csv*
NCAATourneySeedRoundSlots.csv*      TeamConferences.csv*
NCAATourneySeeds.csv*               TeamSpellings.csv*
NCAATourneySlots.csv*               Teams.csv*


In [119]:
# Define file paths
FILE_PATH = 'datasets/kaggle/stage_2/'
NCAATourneyCompactResults_path = FILE_PATH + 'NCAATourneyCompactResults.csv'
NCAATourneySeeds_path = FILE_PATH + 'NCAATourneySeeds.csv'
RegularSeasonCompactResults_path = FILE_PATH + 'RegularSeasonCompactResults.csv'

In [120]:
# Create dataframes from files
NCAATourneyCompactResults = pd.read_csv(NCAATourneyCompactResults_path)
NCAATourneySeeds = pd.read_csv(NCAATourneySeeds_path)
RegularSeasonCompactResults = pd.read_csv(RegularSeasonCompactResults_path)

In [121]:
# Look at dataframes
NCAATourneyCompactResults.head()

Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985     136     1116      63     1234      54    N      0
1    1985     136     1120      59     1345      58    N      0
2    1985     136     1207      68     1250      43    N      0
3    1985     136     1229      58     1425      55    N      0
4    1985     136     1242      49     1325      38    N      0

In [122]:
NCAATourneySeeds.head()

Season Seed  TeamID
0    1985  W01    1207
1    1985  W02    1210
2    1985  W03    1228
3    1985  W04    1260
4    1985  W05    1374

In [123]:
RegularSeasonCompactResults.head()

Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985      20     1228      81     1328      64    N      0
1    1985      25     1106      77     1354      70    H      0
2    1985      25     1112      63     1223      56    H      0
3    1985      25     1165      70     1432      54    H      0
4    1985      25     1192      86     1447      74    H      0

## Create a 'seed' DataFrame

In [124]:
# Define a function that combines the values of two DataFrame columns,
# combining them into a single column with the values separated by an underscore
def get_id(p_row, p_column_names):
    column_values = [p_row[col] for col in p_column_names]
    return '_'.join(map(str, column_values))


# Make a copy of the NCAATourneySeeds DataFrame
seed = NCAATourneySeeds.copy()
# Add an 'id' column to the 'seed' DataFrame,
# using the get_id function to combine 'Season' and 'TeamID'
seed['id'] = seed.apply(lambda row: get_id(row, ['Season', 'TeamID']), axis=1)
# Extract the seed number from the 'Seed' value
seed['seed'] = seed['Seed'].apply(lambda x: int(x[1:3]))
# Extract the region from the 'Seed' value
seed['region'] = seed['Seed'].apply(lambda x: x[0])
# Rename the 'Season' column to 'season' and 'TeamID' to 'team'
seed = seed.rename(columns={'Season': 'season', 'TeamID': 'team'})
# Redefine the 'seed' DataFrame with the columns in this order
seed = seed[['id', 'season', 'team', 'region', 'seed']]
# Sort the 'seed' DataFrame by the 'id' column we created
seed = seed.sort_values(by=['id'])
seed.head()

id  season  team region  seed
22  1985_1104    1985  1104      X     7
25  1985_1112    1985  1112      X    10
24  1985_1116    1985  1116      X     9
58  1985_1120    1985  1120      Z    11
42  1985_1130    1985  1130      Y    11

In [125]:
# Look at NCAATourneyCompactResults
NCAATourneyCompactResults.head()
# Note 

Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985     136     1116      63     1234      54    N      0
1    1985     136     1120      59     1345      58    N      0
2    1985     136     1207      68     1250      43    N      0
3    1985     136     1229      58     1425      55    N      0
4    1985     136     1242      49     1325      38    N      0

## Create a 'final_four' DataFrame

In [126]:
# Create a 'tourney' DataFrame based on NCAATourneyCompactResults
tourney = NCAATourneyCompactResults.copy()
# Create a 'winners' DataFrame
winners = tourney[['Season', 'DayNum', 'WTeamID', 'WScore', 'NumOT']].copy()
# Rename the columns
winners = winners.rename(columns={'WTeamID': 'TeamID', \
                                  'WScore': 'Score'
                                 })
# Create a 'losers' DataFrame
losers = tourney[['Season', 'DayNum', 'LTeamID', 'LScore', 'NumOT']].copy()
# Rename the columns
losers = losers.rename(columns={'LTeamID': 'TeamID', \
                                'LScore': 'Score'
                               })
# Combine the 'winners' and 'losers' DataFrames
results = pd.concat([winners, losers])
# Create a 'final_four' DataFrame for only the teams that played on day 152
final_four = results.loc[results['DayNum'] == 152].copy()
# Create an 'id' column
final_four['id'] = final_four.apply(lambda row: get_id(row, ['Season', 'TeamID']), axis=1)
# Sort the DataFrame by the 'id' column
final_four = final_four[['id']].sort_values(by=['id'])
# Create a 'final_four' column, set it to 1
final_four['final_four'] = str(1) # string
# final_four['final_four'] = 1 # numeric
# Show the first 5 rows
final_four.head()

id final_four
60   1985_1207          1
61   1985_1272          1
60   1985_1385          1
61   1985_1437          1
123  1986_1181          1

## Combine 'seed' and 'final_four' DataFrames

In [127]:
# Merge the 'seed' and 'final_four' DataFrames.
# Left: Keep all the rows from the 'seed' DataFrame,
# even when there's no match in 'final_four'
dataset = pd.merge(seed, final_four, how='left', on='id')
dataset.head()

id  season  team region  seed final_four
0  1985_1104    1985  1104      X     7        NaN
1  1985_1112    1985  1112      X    10        NaN
2  1985_1116    1985  1116      X     9        NaN
3  1985_1120    1985  1120      Z    11        NaN
4  1985_1130    1985  1130      Y    11        NaN

In [128]:
# Set all the 'final_four' column values that aren't 1, to 0
dataset['final_four'] = dataset['final_four'].fillna(value=str(0)) # string
# dataset['final_four'] = dataset['final_four'].fillna(value=0) # numeric
# Show the dataset the way we want it
dataset

id  season  team region  seed final_four
0     1985_1104    1985  1104      X     7          0
1     1985_1112    1985  1112      X    10          0
2     1985_1116    1985  1116      X     9          0
3     1985_1120    1985  1120      Z    11          0
4     1985_1130    1985  1130      Y    11          0
5     1985_1173    1985  1173      Z     9          0
6     1985_1177    1985  1177      W    10          0
7     1985_1181    1985  1181      Y     3          0
8     1985_1192    1985  1192      Z    16          0
9     1985_1207    1985  1207      W     1          1
10    1985_1208    1985  1208      W     6          0
11    1985_1210    1985  1210      W     2          0
12    1985_1228    1985  1228      W     3          0
13    1985_1229    1985  1229      Y     9          0
14    1985_1233    1985  1233      W    13          0
15    1985_1234    1985  1234      X     8          0
16    1985_1235    1985  1235      Y    13          0
17    1985_1242    1985  1242      Z     3          0
18    1985_1246    1985  1246      X    12          0
19    1985_1250    1985  1250      W    16          0
20    1985_1256    1985  1256      Y     5          0
21    1985_1260    1985  1260      W     4          0
22    1985_1261    1985  1261      Z     4          0
23    1985_1267    1985  1267      X    15          0
24    1985_1268    1985  1268      Z     5          0
25    1985_1272    1985  1272      Y     2          1
26    1985_1273    1985  1273      W    15          0
27    1985_1275    1985  1275      Z    12          0
28    1985_1276    1985  1276      Z     1          0
29    1985_1277    1985  1277      Y    10          0
...         ...     ...   ...    ...   ...        ...
2256  2019_1305    2019  1305      X     7          0
2257  2019_1308    2019  1308      Y    12          0
2258  2019_1314    2019  1314      Y     1          0
2259  2019_1318    2019  1318      Y    13          0
2260  2019_1326    2019  1326      Y    11          0
2261  2019_1328    2019  1328      Z     9          0
2262  2019_1330    2019  1330      Z    14          0
2263  2019_1332    2019  1332      Z    12          0
2264  2019_1341    2019  1341      X    16          0
2265  2019_1345    2019  1345      Z     3          0
2266  2019_1371    2019  1371      Y    10          0
2267  2019_1385    2019  1385      X    11          0
2268  2019_1387    2019  1387      W    13          0
2269  2019_1388    2019  1388      Z    11          0
2270  2019_1393    2019  1393      X     8          0
2271  2019_1396    2019  1396      W    11          0
2272  2019_1397    2019  1397      Z     2          0
2273  2019_1403    2019  1403      X     3          0
2274  2019_1414    2019  1414      Z    13          0
2275  2019_1416    2019  1416      W     9          0
2276  2019_1429    2019  1429      Y     8          0
2277  2019_1433    2019  1433      W     8          0
2278  2019_1436    2019  1436      X    13          0
2279  2019_1437    2019  1437      Z     6          0
2280  2019_1438    2019  1438      Z     1          0
2281  2019_1439    2019  1439      W     4          0
2282  2019_1449    2019  1449      Y     9          0
2283  2019_1458    2019  1458      Z     5          0
2284  2019_1459    2019  1459      Y     7          0
2285  2019_1463    2019  1463      W    14          0

[2286 rows x 6 columns]

## Logistic regression

In [129]:
# Create a historical DataFrame (exclude 2019)
dataset_historical = dataset.loc[dataset['season'] != 2019]
dataset_historical.head()

id  season  team region  seed final_four
0  1985_1104    1985  1104      X     7          0
1  1985_1112    1985  1112      X    10          0
2  1985_1116    1985  1116      X     9          0
3  1985_1120    1985  1120      Z    11          0
4  1985_1130    1985  1130      Y    11          0

In [130]:
# Createa 2019 DataFrame
dataset_2019 = dataset.loc[dataset['season'] == 2019]
dataset_2019.head()

id  season  team region  seed final_four
2218  2019_1101    2019  1101      Y    15          0
2219  2019_1113    2019  1113      X    11          0
2220  2019_1120    2019  1120      Y     5          0
2221  2019_1124    2019  1124      X     9          0
2222  2019_1125    2019  1125      W    11          0

In [131]:
# We'll use 'X' for our predictors and 'y' for our target
# We just want the values, and we want it as an array instead of a DataFrame
X = dataset_historical.iloc[:, 4:5].values
X

array([[ 7],
       [10],
       [ 9],
       ...,
       [ 4],
       [14],
       [ 1]])

In [132]:
y = dataset_historical.iloc[:, 5].values
y

array(['0', '0', '0', ..., '0', '0', '0'], dtype=object)

In [133]:
# Split X and y into training and testing datasets

# # Via train_test_split
# from sklearn.model_selection import train_test_split
# X_train, X_test, \
# y_train, y_test = \
# train_test_split(X, \
#                  y, \
#                  test_size=0.3, \
#                  random_state=0 \
#                 )

# Via permutation
import numpy as np
# length of the dataset
length = dataset_historical.shape[0]
# We only want 70% of the data for the training set
train_index_stop = int(length * 0.7)
# Create a permutation
permutation = np.random.RandomState(0).permutation(length)
# Take just the values up to the train_index_stop
train_permutation = permutation[:train_index_stop]
# Take the values after the train_index_stop
test_permutation = permutation[train_index_stop:]

# Create the training and testing data
X_train = X[train_permutation]
X_test = X[test_permutation]
y_train = y[train_permutation]
y_test = y[test_permutation]

In [134]:
X_train

array([[ 9],
       [ 7],
       [10],
       ...,
       [ 6],
       [ 6],
       [15]])

In [135]:
y_train

array(['0', '0', '0', ..., '0', '0', '0'], dtype=object)

In [136]:
# We want the predictors to be on the same scale
# (mean of 0, standard deviation of 1)
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
print('before')
print(X_train)
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
# Don't worry about the warning
print('after')
print(X_train)

before
[[ 9]
 [ 7]
 [10]
 ...
 [ 6]
 [ 6]
 [15]]
after
[[ 0.07074208]
 [-0.35729575]
 [ 0.28476099]
 ...
 [-0.57131467]
 [-0.57131467]
 [ 1.35485557]]


/Users/ehelander/anaconda3/lib/python3.6/site-packages/sklearn/utils/validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [137]:
# Fit a LogisticRegression object to training set
from sklearn.linear_model import LogisticRegression
classifierObj = LogisticRegression(random_state=0)
classifierObj.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [138]:
y_train

array(['0', '0', '0', ..., '0', '0', '0'], dtype=object)

In [139]:
# Making predictions on the test set
y_pred = classifierObj.predict(X_test)

In [140]:
# Evaluating the predictions using a confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[628   0]
 [ 38   0]]


In [141]:
# So, we predicted 0 out of 43 correctly.
# This is to be expected, because the model, by default,
# will only predict a class if it has a greater than
# 50% probability. None of these teams do.

In [142]:
# Predict the probability of [0, 1]
prob = classifierObj.predict_proba(X_test)
prob

array([[0.99570463, 0.00429537],
       [0.98996664, 0.01003336],
       [0.8323262 , 0.1676738 ],
       ...,
       [0.8323262 , 0.1676738 ],
       [0.97674256, 0.02325744],
       [0.99880349, 0.00119651]])

In [143]:
test_predicted_probability = prob[:, 1]
print(test_predicted_probability.shape)
# Predicted y probabilities
test_predicted_probability

(666,)


array([0.00429537, 0.01003336, 0.1676738 , 0.00078094, 0.1676738 ,
       0.1676738 , 0.11616253, 0.1676738 , 0.03521208, 0.00078094,
       0.1676738 , 0.32124712, 0.00183281, 0.23592982, 0.02325744,
       0.00078094, 0.0152971 , 0.03521208, 0.32124712, 0.05297826,
       0.1676738 , 0.00280654, 0.1676738 , 0.00078094, 0.01003336,
       0.23592982, 0.02325744, 0.01003336, 0.0065688 , 0.03521208,
       0.00119651, 0.00429537, 0.02325744, 0.00078094, 0.00280654,
       0.03521208, 0.00183281, 0.0065688 , 0.02325744, 0.00429537,
       0.23592982, 0.11616253, 0.05297826, 0.23592982, 0.11616253,
       0.1676738 , 0.23592982, 0.0152971 , 0.0152971 , 0.1676738 ,
       0.32124712, 0.32124712, 0.07897458, 0.05297826, 0.00119651,
       0.03521208, 0.0065688 , 0.02325744, 0.1676738 , 0.23592982,
       0.02325744, 0.03521208, 0.32124712, 0.00078094, 0.00119651,
       0.1676738 , 0.05297826, 0.03521208, 0.0152971 , 0.02325744,
       0.32124712, 0.00429537, 0.1676738 , 0.00429537, 0.07897

In [144]:
# Actual y values
y_test

array(['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1',
       '0', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '1', '0', '1', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0

In [145]:
# Get, show original data for test split
dataset_historical_test = dataset_historical.loc[test_permutation]
dataset_historical_test.head()

id  season  team region  seed final_four
1746  2012_1143    2012  1143      X    12          0
753   1996_1400    1996  1400      X    10          0
462   1992_1199    1992  1199      X     3          0
673   1995_1291    1995  1291      Z    16          0
1682  2011_1140    2011  1140      Y     3          0

In [146]:
# Add predicted probability to historical data
dataset_historical_test['predicted_probability'] = test_predicted_probability
dataset_historical_test

id  season  team region  seed final_four  predicted_probability
1746  2012_1143    2012  1143      X    12          0               0.004295
753   1996_1400    1996  1400      X    10          0               0.010033
462   1992_1199    1992  1199      X     3          0               0.167674
673   1995_1291    1995  1291      Z    16          0               0.000781
1682  2011_1140    2011  1140      Y     3          0               0.167674
1463  2007_1401    2007  1401      X     3          0               0.167674
1201  2003_1390    2003  1390      X     4          0               0.116163
2203  2018_1397    2018  1397      Y     3          0               0.167674
424   1991_1345    1991  1345      W     7          0               0.035212
325   1990_1131    1990  1131      W    16          0               0.000781
664   1995_1268    1995  1268      X     3          0               0.167674
350   1990_1277    1990  1277      Y     1          0               0.321247
447   1991_1462    1991  1462      Y    14          0               0.001833
1625  2010_1243    2010  1243      Z     2          0               0.235930
1041  2001_1208    2001  1208      W     8          0               0.023257
1221  2004_1106    2004  1106      W    16          0               0.000781
1712  2011_1330    2011  1330      Y     9          0               0.015297
1149  2002_1448    2002  1448      X     7          0               0.035212
387   1991_1116    1991  1116      X     1          0               0.321247
1369  2006_1231    2006  1231      X     6          0               0.052978
1743  2012_1124    2012  1124      Y     3          0               0.167674
1337  2005_1418    2005  1418      W    13          0               0.002807
754   1996_1403    1996  1403      W     3          0               0.167674
138   1987_1193    1987  1193      Y    16          0               0.000781
451   1992_1140    1992  1140      X    10          0               0.010033
1194  2003_1338    2003  1338      Y     2          0               0.235930
699   1995_1443    1995  1443      Y     8          0               0.023257
1157  2003_1120    2003  1120      W    10          0               0.010033
2043  2016_1276    2016  1276      W    11          0               0.006569
830   1997_1458    1997  1458      W     7          0               0.035212
...         ...     ...   ...    ...   ...        ...                    ...
1207  2003_1421    2003  1421      X    16          0               0.000781
151   1987_1246    1987  1246      X     8          0               0.023257
714   1996_1163    1996  1163      Y     1          0               0.321247
544   1993_1276    1993  1276      Z     1          1               0.321247
639   1994_1458    1994  1458      Z     9          0               0.015297
423   1991_1343    1991  1343      W     8          0               0.023257
659   1995_1242    1995  1242      Y     1          0               0.321247
797   1997_1269    1997  1269      W    11          0               0.006569
2201  2018_1393    2018  1393      X    11          0               0.006569
2008  2015_1452    2015  1452      Y     5          0               0.078975
99    1986_1299    1986  1299      X    16          0               0.000781
1871  2013_1424    2013  1424      W     5          0               0.078975
2046  2016_1314    2016  1314      W     1          1               0.321247
755   1996_1409    1996  1409      X    11          0               0.006569
976   2000_1220    2000  1220      W    14          0               0.001833
2163  2018_1172    2018  1172      Y    12          0               0.004295
1940  2014_1451    2014  1451      Z    16          0               0.000781
2120  2017_1323    2017  1323      X     5          0               0.078975
537   1993_1253    1993  1253      Z    11          0               0.006569
1701  2011_1266    2011  1266      W    11          0               0.006569
2135  201

In [150]:
X_2019 = dataset_2019.iloc[:, 4:5].values
# y_2019 = dataset_2019.iloc[:, 5].values

# classifierObj.predict_proba(X_2019)[:, 1]

dataset_2019_output = dataset_2019.copy()
dataset_2019_output['predicted_probability'] = classifierObj.predict_proba(X_2019)[:, 1]
dataset_2019_output

id  season  team region  seed final_four  predicted_probability
2218  2019_1101    2019  1101      Y    15          0           1.790480e-15
2219  2019_1113    2019  1113      X    11          0           5.242528e-12
2220  2019_1120    2019  1120      Y     5          0           8.306105e-07
2221  2019_1124    2019  1124      X     9          0           2.836785e-10
2222  2019_1125    2019  1125      W    11          0           5.242528e-12
2223  2019_1133    2019  1133      W    15          0           1.790480e-15
2224  2019_1138    2019  1138      X     6          0           1.129158e-07
2225  2019_1153    2019  1153      Z     7          0           1.535013e-08
2226  2019_1159    2019  1159      Z    15          0           1.790480e-15
2227  2019_1181    2019  1181      W     1          0           2.426131e-03
2228  2019_1192    2019  1192      X    16          0           2.434034e-16
2229  2019_1196    2019  1196      X    10          0           3.856413e-11
2230  2019_1199    2019  1199      X     4          0           6.109954e-06
2231  2019_1205    2019  1205      Z    16          0           2.434034e-16
2232  2019_1209    2019  1209      Y    14          0           1.317080e-14
2233  2019_1211    2019  1211      X     1          0           2.426131e-03
2234  2019_1222    2019  1222      Y     3          0           4.494320e-05
2235  2019_1233    2019  1233      Y    16          0           2.434034e-16
2236  2019_1234    2019  1234      Z    10          0           3.856413e-11
2237  2019_1235    2019  1235      Y     6          0           1.129158e-07
2238  2019_1242    2019  1242      Y     4          0           6.109954e-06
2239  2019_1243    2019  1243      Z     4          0           6.109954e-06
2240  2019_1246    2019  1246      Y     2          0           3.305086e-04
2241  2019_1251    2019  1251      W    12          0           7.126855e-13
2242  2019_1257    2019  1257      W     7          0           1.535013e-08
2243  2019_1261    2019  1261      W     3          0           4.494320e-05
2244  2019_1266    2019  1266      X     5          0           8.306105e-07
2245  2019_1268    2019  1268      W     6          0           1.129158e-07
2246  2019_1276    2019  1276      X     2          0           3.305086e-04
2247  2019_1277    2019  1277      W     2          0           3.305086e-04
...         ...     ...   ...    ...   ...        ...                    ...
2256  2019_1305    2019  1305      X     7          0           1.535013e-08
2257  2019_1308    2019  1308      Y    12          0           7.126855e-13
2258  2019_1314    2019  1314      Y     1          0           2.426131e-03
2259  2019_1318    2019  1318      Y    13          0           9.688467e-14
2260  2019_1326    2019  1326      Y    11          0           5.242528e-12
2261  2019_1328    2019  1328      Z     9          0           2.836785e-10
2262  2019_1330    2019  1330      Z    14          0           1.317080e-14
2263  2019_1332    2019  1332      Z    12          0           7.126855e-13
2264  2019_1341    2019  1341      X    16          0           2.434034e-16
2265  2019_1345    2019  1345      Z     3          0           4.494320e-05
2266  2019_1371    2019  1371      Y    10          0           3.856413e-11
2267  2019_1385    2019  1385      X    11          0           5.242528e-12
2268  2019_1387    2019  1387      W    13          0           9.688467e-14
2269  2019_1388    2019  1388      Z    11          0           5.242528e-12
2270  2019_1393    2019  1393      X     8          0           2.086744e-09
2271  2019_1396    2019  1396      W    11          0           5.242528e-12
2272  2019_1397    2019  1397      Z     2          0           3.305086e-04
2273  2019_1403    2019  1403      X     3          0           4.494320e-05
2274  2019_1414    2019  1414      Z    13          0           9.688467e-14
2275  2019_1416    2019  1416      W     9          0           2.836785e-10
2276  201